# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               THE SIMPLETON REPORT
tagline:             THE ONLY NEWS SOURCE THAT MAKES SENSE TO IDIOTS
url:                 http://thesimpletonreport.github.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Anon Pseudo
  url:               http://thesimpletonreport.github.com
  email:             thesimpletonreport@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/thesimpletonreport/thesimpletonreport.github.com
